Update postinst target and changelog

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -8,9 +8,13 @@ case "$1" in
 			/etc/init.d/tlsdate /etc/init.d/tlsdated 0.0.7-1.3~ -- "$@"
 		dpkg-maintscript-helper mv_conffile \
 			/etc/default/tlsdate /etc/default/tlsdated 0.0.7-1.3~ -- "$@"
-		;;
-	install)
-		tlsdate --showtime=raw -n > /var/cache/tlsdated/timestamp
+		# On Debian GNU/Linux, we run tlsdated - so cache a recent stamp
+		# if possible or fail silently...
+		if [ "$(uname)" = "Linux" ];then
+			mkdir -p /var/cache/tlsdated/;
+			tlsdate --showtime=raw -n > /var/cache/tlsdated/timestamp \
+			|| true;
+		fi
 		;;
 	*)
 		;;
